name: Sync Reservations to Notion

permissions:
  contents: write

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose platform to sync'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - airbnb
          - booking

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run sync script
        run: node src/index.js
        continue-on-error: true
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          AIRBNB_ICS: ${{ secrets.AIRBNB_ICS }}
          BOOKING_ICS: ${{ secrets.BOOKING_ICS }}
          PLATFORM: ${{ github.event.inputs.platform || 'all' }}
          DEBUG_CACHE: false

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || (git commit -m "chore: update .ics files from reservation-sync" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }})
