name: Sync Reservations to Notion

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:
    inputs:
      platform:
        description: 'Choose platform to sync'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - airbnb
          - booking

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run sync script
        run: node src/index.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          AIRBNB_ICS: ${{ secrets.AIRBNB_ICS }}
          BOOKING_ICS: ${{ secrets.BOOKING_ICS }}
          PLATFORM: ${{ github.event.inputs.platform || 'all' }}